#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

#/ Usage: fuzzy-checkout
#/ Description:
#/   Lists all branches by last commit date in a fuzzy find cli provided by
#/   `fzf`. The selected branch is sent to `git checkout`. Remote branch
#/   names are stripped of `remotes/<origin name>/` for compatibility.
#/
#/ Options:
#/   --help: Display this help message
#/           Use git checkout --help to see help for `checkout`
#/
#/ Dependencies:
#/  * https://github.com/junegunn/fzf
#/
#/ Notes:
#/  All other commands except for `--help` are forwarded to `git checkout`,
#/  bypassing fuzzy finding.
#/
#/  Place this script in your PATH, and alias it in your `.gitconfig`
#/
usage() { grep '^#/' "$0" | cut -c4- ; exit 0 ; }
expr "$*" : ".*--help" > /dev/null && usage

info()    { echo "[INFO]    $@" ; }
fatal()   { echo "[FATAL]   $@" ; exit 1 ; }

fuzzy-checkout() {
  local branches branch
  if [[ !(-x "$(which fzf)") ]]; then
    fatal "fzf not found. Check path for fzf, or install fzf."
  fi

  branches=$(git branch --all --sort=-committerdate | grep -v HEAD) &&
  # Taken and modified from fzf wiki.
  branch=$(echo "$branches" |
           fzf -d $(( 2 + $(wc -l <<< "$branches") )) +m) &&
  git checkout $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}

normal-checkout() {
  git checkout "$@"
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    if [[ $# -eq 0 ]]; then
      fuzzy-checkout;
    else
      normal-checkout "$@";
    fi
fi
